FROM php:8.2-fpm

# Install dependencies
RUN apt update
RUN apt install -y software-properties-common

# Install composer
RUN apt install -y curl
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

COPY . /var/www
WORKDIR /var/www

RUN chown -R www-data:www-data /var/www

RUN composer install

EXPOSE 9000