version: '3.9'

networks:
  sales-app:
    driver: bridge

services:
  sales-php:
    build: 
      context: .
      dockerfile: ./docker/php/DockerFile
    container_name: sales-php-container
    image: sales-php-app
    tty: true
    volumes:
      - ./:/var/www
    ports:
      - "9000:9000"
    depends_on:
      - sales-mysql
    networks:
      - sales-app

  sales-nginx:
    image: nginx:latest
    container_name: sales-nginx-container
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "81:80"
      - "443:443"
    links:
      - sales-php
    depends_on:
      - sales-php
    networks:
      - sales-app
  
  sales-mysql:
    image: mysql:latest
    container_name: sales-mysql-container
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: strong_password
      MYSQL_DATABASE: sales
      MYSQL_USER: sales
      MYSQL_PASSWORD: strong_password
    networks:
      - sales-app